### ISSUE TITLE
[Service] Hosting

### ISSUE THREAD

**Issue by hellodhlyn** [lynlab/luppiter#12]
## Flows

User create a **hosting instance**. Each instance has a backend like a Luppiter Storage, and a frontend domain looks like `xxxxxxxxxxxxxxxxxxxx.luppiter.dev`.
User can set CNAME DNS records for the issued domain.

## TODOs

- [x] Proxy server (will be provided with separated projects)
- [x] Instance management APIs
- [x] Automated TLS supports using Let's Encrypt
